return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'c_sharp',
      'razor',
      'sql',
      'yaml',
      'vue',
      'svelte',
      'scss',
      'proto',
      'powershell',
      'angular',
      'dockerfile',
      'go',
      'json',
      'rst',
      'terraform',
      'javascript',
      'toml',
      'bash',
      'c',
      'diff',
      'html',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'query',
      'vim',
      'vimdoc',
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'ruby' },
    },
    indent = { enable = true, disable = { 'ruby' } },
  },
}
